### PR TITLE
Upgrade nanorand to 0.7

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Just a dependency bump. Should be semver compatible

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
CI failure seems unrelated

**Comment by zesterer** [comment]
Thanks!

**Comment by cwfitzgerald** [comment]
Any chance of getting a release with this?

**Comment by zesterer** [comment]
I've just published `0.10.12`, which includes this change.

**Comment by cwfitzgerald** [comment]
Thank you so much!

**Pull request merged**
