### PR TITLE
Format code using 'cargo fmt'

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by Restioson** [comment]
Might want to re-do this when flavour-refactor is merged. This would probably create quite a few merge conflicts.

**Comment by zesterer** [comment]
This is definitely on my list of things to do. As @Restioson says, we're currently working on the `flavour-refactor` branch which is yielding very impressive performance improvements. Once this is merged we can format everything.

**Comment by Atul9** [comment]
ok, I can rebase & format the code when that PR is merged.

**Comment by zesterer** [comment]
I'm going to close this because master has changed significant recently and this PR probably isn't worth rebasing.

**Pull request closed without merging**
